//> using target.platform "scala-js"
package dapr4s.test.integration

import dapr4s.*
import dapr4s.given
import munit.FunSuite
import scala.concurrent.duration.{Duration, DurationInt}
import scala.scalajs.js
import unsafeExceptions.canThrowAny
import JsItEnv.*

/** [[CryptoCapability]] against a real `crypto.dapr.localstorage` component, backed by an RSA key generated by
  * `scripts/js-integration-env.sh up` into the shared resource dir's `keys/rsa-key` and mounted into the sidecar — the
  * Scala.js twin of [[CryptoCapabilityServerTest]].
  *
  * Crypto is gRPC-only in the JS SDK (the HTTP client throws `HTTPNotSupportedError`), so like
  * [[ConfigurationJsIntegrationTest]] this suite exercises the lazily created gRPC-protocol client over the real alpha1
  * streaming wire API.
  */
@scala.caps.assumeSafe
class CryptoJsIntegrationTest extends FunSuite:

  override def munitTimeout: Duration = 120.seconds

  test("crypto: encryptString then decryptString round-trips the original text"):
    js.async {
      Dapr(clientConfig).run:
        DaprCapability.crypto(CryptoStore) {
          val plaintext = "the quick brown fox"
          val cipher = CryptoCapability.encryptString(CryptoKey, plaintext, KeyWrapAlgorithm.Rsa)
          assert(cipher.nonEmpty, "ciphertext should not be empty")
          assertEquals(CryptoCapability.decryptString(cipher), plaintext)
        }
    }.toFuture

  test("crypto: encrypt then decrypt round-trips raw bytes"):
    js.async {
      Dapr(clientConfig).run:
        DaprCapability.crypto(CryptoStore) {
          val data = Charsets.encodeString("payload-bytes", Charsets.Utf8)
          val cipher = CryptoCapability.encrypt(CryptoKey, data, KeyWrapAlgorithm.Rsa)
          assertEquals(CryptoCapability.decrypt(cipher), data)
        }
    }.toFuture
