//> using target.platform "scala-js"
package dapr4s.internal.facade

import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobal, JSImport}

// ---------------------------------------------------------------------------
// Scala.js facades for express 4 (a dependency of `@dapr/dapr`, so always
// present in node_modules) plus the two Node builtins the server lifecycle
// needs (`http.Server`, `process`). Used exclusively by
// `dapr4s.internal.DaprAppServer` — the JS twin of the JVM app-channel server,
// which hand-rolls the Dapr app-channel HTTP protocol instead of using the
// SDK's `DaprServer` (whose callbacks strip the CloudEvent envelope and
// constrain HTTP verbs).
//
// Signatures verified against the installed sources in node_modules/express
// (v4.22.2): lib/express.js, lib/application.js, lib/request.js,
// lib/response.js, lib/router/. Runtime-verified by a packaged Scala.js smoke
// app under BOTH CommonJS and ES module kinds.
// ---------------------------------------------------------------------------

/** An express route handler. Express invokes handlers with `(req, res, next)`; we never call `next` from a terminal
  * route handler, and a JS function created from a `js.Function2` lambda simply ignores the extra argument (standard
  * JavaScript arity semantics).
  */
private[internal] type ExpressHandler = js.Function2[ExpressRequest, ExpressResponse, Unit]

/** An express middleware function `(req, res, next)`. Express distinguishes error-handling middleware by
  * `fn.length == 4`, so a 3-parameter function is always treated as ordinary middleware.
  */
private[internal] type ExpressMiddleware = js.Function3[ExpressRequest, ExpressResponse, js.Function0[Unit], Unit]

/** Facade for the express module itself (`lib/express.js`).
  *
  * ==Why `JSImport.Default` (and not `Namespace`)==
  *
  * express is a classic CommonJS module: `module.exports = createApplication` — a '''callable function''' that also
  * carries the middleware factories (`text`, `json`, ...) as properties. The two Scala.js module kinds bind a default
  * import differently:
  *
  *   - under `jsModuleKind commonjs`, Scala.js resolves `JSImport.Default` through its `$moduleDefault` interop helper
  *     (`m.__esModule ? m.default : m`); express sets no `__esModule` flag, so we get `module.exports` itself;
  *   - under `jsModuleKind es` (the Wasm/JSPI production target), `import { default as e } from "express"` binds Node's
  *     CJS↔ESM interop default, which is again `module.exports`.
  *
  * `JSImport.Namespace` would break under ES modules: an `import * as ns` namespace object is '''never callable''', so
  * `express()` would throw `TypeError: ns is not a function`. `Default` is the only binding that yields the callable
  * function under both module kinds (verified at runtime under both).
  *
  * The `apply` member denotes calling the imported value itself as a function (standard Scala.js facade rule for
  * members named `apply` without `@JSName`).
  */
@js.native
@JSImport("express", JSImport.Default)
private[internal] object Express extends js.Object:

  /** `express()` — create an application (`lib/express.js` `createApplication`). */
  def apply(): ExpressApp = js.native

  /** `express.text(options)` — the re-exported body-parser text middleware (`exports.text = bodyParser.text`). With
    * `type` set to the catch-all media range (star-slash-star) it captures every request body as a raw string in
    * `req.body`, leaving JSON parsing to our dispatch code (mirroring the JVM server's raw `readBody`). Note
    * body-parser's quirk: for requests it skips (no body, or no `Content-Type` to match), it sets `req.body = {}`, not
    * a string — see `ExpressRequest.body`.
    */
  def text(options: ExpressTextOptions): ExpressMiddleware = js.native

/** Options for [[Express.text]] (body-parser `lib/types/text.js`).
  *
  * @param `type`
  *   the media type(s) to match (via type-is); the catch-all media range (star-slash-star) matches any present
  *   `Content-Type`
  * @param limit
  *   maximum body size in bytes when passed as a number (`typeof opts.limit === 'number'` skips `bytes.parse`)
  */
private[internal] final class ExpressTextOptions(
    val `type`: js.UndefOr[String] = js.undefined,
    val limit: js.UndefOr[Double] = js.undefined,
) extends js.Object

/** The express application (`lib/application.js`). The HTTP-verb methods are generated by the `methods.forEach` block
  * (line 489); each registers a route handler for that verb only. We always pass a path AND a handler, so the
  * single-argument `app.get(setting)` settings-getter overload is never hit.
  */
@js.native
private[internal] trait ExpressApp extends js.Object:

  /** Mount application-wide middleware (`app.use(fn)`); runs in registration order before/after routes. */
  def use(middleware: ExpressMiddleware): Unit = js.native

  def get(path: String, handler: ExpressHandler): Unit = js.native
  def post(path: String, handler: ExpressHandler): Unit = js.native
  def put(path: String, handler: ExpressHandler): Unit = js.native
  def delete(path: String, handler: ExpressHandler): Unit = js.native

  /** Register `handler` for the path under '''every''' HTTP method (`app.all`, line 514). */
  def all(path: String, handler: ExpressHandler): Unit = js.native

  /** `app.listen` delegates verbatim to Node's `net.Server.listen` (`http.createServer(this)` + `server.listen.apply`,
    * line 633). The `(port, backlog, callback)` arity is supported by Node's argument normalisation: a numeric second
    * argument is taken as the backlog (`toNumber(args[1])` in `net.js`). Returns the underlying `http.Server`.
    */
  def listen(port: Int, callback: js.Function0[Unit]): NodeHttpServer = js.native
  def listen(port: Int, backlog: Int, callback: js.Function0[Unit]): NodeHttpServer = js.native

/** The express request (`lib/request.js`, augmented by the router). Only the members the dispatch layer reads. */
@js.native
private[internal] trait ExpressRequest extends js.Object:

  /** Named route parameters (`:name` segments), URI-decoded by the router (`lib/router/layer.js` `decode_param`). */
  def params: js.Dictionary[String] = js.native

  /** The parsed body. With the [[Express.text]] middleware mounted this is the raw body '''string''' — except for
    * requests body-parser skips (no body / no `Content-Type`), where it is the `{}` placeholder object body-parser
    * assigns unconditionally (`req.body = req.body || {}`). Callers must therefore type-test for `String`.
    */
  def body: js.Any = js.native

  /** The HTTP verb, upper-case (Node `IncomingMessage.method`). */
  def method: String = js.native

  /** The URL pathname, query string excluded (getter at `lib/request.js` line 412). */
  def path: String = js.native

  /** `req.get(name)`/`req.header(name)`: the request header, or `undefined` when absent. */
  def get(name: String): js.UndefOr[String] = js.native

/** The express response (`lib/response.js`). Only the members the dispatch layer writes. */
@js.native
private[internal] trait ExpressResponse extends js.Object:

  /** Set the response status code (line 67); returns `this` for chaining. */
  def status(code: Int): this.type = js.native

  /** Send a string body and finish the response (line 111). Sets `Content-Length`; the content type defaults to
    * `text/html` for strings unless set beforehand via [[`type`]].
    */
  def send(body: String): Unit = js.native

  /** `res.type(t)` (line 619): set `Content-Type`; values containing `/` are used verbatim. */
  def `type`(contentType: String): this.type = js.native

  /** Finish the response without a body (inherited Node `ServerResponse.end`) — the express twin of the JVM's
    * `exchange.sendResponseHeaders(code, -1)`.
    */
  def end(): Unit = js.native

/** The Node `http.Server` returned by [[ExpressApp.listen]] — only the lifecycle members the shutdown path needs. */
@js.native
private[internal] trait NodeHttpServer extends js.Object:

  /** Stop accepting new connections; `callback` fires once all in-flight connections have closed. */
  def close(callback: js.Function0[Unit]): Unit = js.native

  /** Subscribe to a server event; `"error"` delivers bind failures (e.g. `EADDRINUSE`) as an `Error`. */
  def on(event: String, listener: js.Function1[js.Error, Unit]): js.Any = js.native

/** The Node `process` global — signal handling and explicit exit for the shutdown path. */
@js.native
@JSGlobal("process")
private[internal] object NodeProcess extends js.Object:

  /** Register a signal listener (`"SIGINT"`, `"SIGTERM"`). Once registered, Node's default terminate-on-signal
    * behaviour is replaced — the listener '''must''' eventually call [[exit]] itself.
    */
  def on(event: String, listener: js.Function0[Unit]): js.Any = js.native

  /** Terminate the process with the given exit code. */
  def exit(code: Int): Nothing = js.native
