package dapr4s.workflow

import dapr4s.*

import language.experimental.safe

import scala.concurrent.duration.FiniteDuration

/** Unique identifier of a workflow instance.
  *
  * Auto-generated by [[AccessWorkflowCapability.start]] when not specified, or supplied explicitly via
  * [[AccessWorkflowCapability.startWithId]]. Used to target subsequent operations on a [[WorkflowInstanceCapability]]
  * (status, suspend, resume, terminate, raiseEvent, …). May be empty when auto-generated (the sidecar assigns a
  * UUID-based value).
  */
opaque type WorkflowInstanceId = String
object WorkflowInstanceId:
  def apply(s: String): WorkflowInstanceId = s
  extension (id: WorkflowInstanceId) def value: String = id

  /** Fluent client-side operations targeting this instance.
    *
    * Each method narrows the [[AccessWorkflowCapability]] in the enclosing `using` context to this instance
    * (`cap.apply(id)`) and forwards, so `id.suspend()` reads as a method on the instance rather than
    * `cap.apply(id).suspend()`:
    * {{{
    *   def pauseOrder(id: WorkflowInstanceId)(using AccessWorkflowCapability): Unit =
    *     id.suspend()
    * }}}
    */
  extension (id: WorkflowInstanceId)
    /** Fetch the current status snapshot. Returns `None` if the instance does not exist.
      *
      * @see
      *   [[WorkflowInstanceCapability.getStatus]]
      */
    def getStatus(using cap: AccessWorkflowCapability): Option[WorkflowSnapshot] =
      cap.apply(id).getStatus()

    /** Suspend this running instance (can be resumed later).
      *
      * @see
      *   [[WorkflowInstanceCapability.suspend]]
      */
    def suspend()(using cap: AccessWorkflowCapability): Unit =
      cap.apply(id).suspend()

    /** Resume this previously suspended instance.
      *
      * @see
      *   [[WorkflowInstanceCapability.resume]]
      */
    def resume()(using cap: AccessWorkflowCapability): Unit =
      cap.apply(id).resume()

    /** Terminate this instance immediately.
      *
      * @see
      *   [[WorkflowInstanceCapability.terminate]]
      */
    def terminate()(using cap: AccessWorkflowCapability): Unit =
      cap.apply(id).terminate()

    /** Send an external event to this waiting instance.
      *
      * @see
      *   [[WorkflowInstanceCapability.raiseEvent]]
      */
    def raiseEvent[E: JsonCodec](eventName: EventName, payload: E)(using cap: AccessWorkflowCapability): Unit =
      cap.apply(id).raiseEvent(eventName, payload)

    /** Block until this instance completes (or the timeout expires). Returns the final snapshot, or `None` if the
      * instance was not found.
      *
      * @see
      *   [[WorkflowInstanceCapability.waitForCompletion]]
      */
    def waitForCompletion(timeout: FiniteDuration)(using cap: AccessWorkflowCapability): Option[WorkflowSnapshot] =
      cap.apply(id).waitForCompletion(timeout)

    /** Purge this instance's state from the state store. Returns `true` if purged.
      *
      * @see
      *   [[WorkflowInstanceCapability.purge]]
      */
    def purge()(using cap: AccessWorkflowCapability): Boolean =
      cap.apply(id).purge()
