package dapr4s

import language.experimental.safe

import scala.concurrent.duration.FiniteDuration

/** Unique identifier of a workflow instance.
  *
  * Auto-generated by [[WorkflowCapability.start]] when not specified, or supplied explicitly via
  * [[WorkflowCapability.startWithId]]. Used to target subsequent operations such as [[WorkflowCapability.getStatus]],
  * [[WorkflowCapability.suspend]], [[WorkflowCapability.resume]], [[WorkflowCapability.terminate]], and
  * [[WorkflowCapability.raiseEvent]]. May be empty when auto-generated (the sidecar assigns a UUID-based value).
  */
opaque type WorkflowInstanceId = String
object WorkflowInstanceId:
  def apply(s: String): WorkflowInstanceId = s
  extension (id: WorkflowInstanceId) def value: String = id

  /** Fluent client-side operations targeting this instance.
    *
    * Each method forwards to the [[WorkflowCapability]] in the enclosing `using` context, so `id.suspend()` reads as a
    * method on the instance rather than `WorkflowCapability.suspend(id)`:
    * {{{
    *   def pauseOrder(id: WorkflowInstanceId)(using WorkflowCapability): Unit =
    *     id.suspend()
    * }}}
    */
  extension (id: WorkflowInstanceId)
    /** Fetch the current status snapshot. Returns `None` if the instance does not exist.
      *
      * @see
      *   [[WorkflowCapability.getStatus]]
      */
    def getStatus(using cap: WorkflowCapability): Option[WorkflowSnapshot] =
      cap.getStatus(id)

    /** Suspend this running instance (can be resumed later).
      *
      * @see
      *   [[WorkflowCapability.suspend]]
      */
    def suspend()(using cap: WorkflowCapability): Unit =
      cap.suspend(id)

    /** Resume this previously suspended instance.
      *
      * @see
      *   [[WorkflowCapability.resume]]
      */
    def resume()(using cap: WorkflowCapability): Unit =
      cap.resume(id)

    /** Terminate this instance immediately.
      *
      * @see
      *   [[WorkflowCapability.terminate]]
      */
    def terminate()(using cap: WorkflowCapability): Unit =
      cap.terminate(id)

    /** Send an external event to this waiting instance.
      *
      * @see
      *   [[WorkflowCapability.raiseEvent]]
      */
    def raiseEvent[E: JsonCodec](eventName: EventName, payload: E)(using cap: WorkflowCapability): Unit =
      cap.raiseEvent(id, eventName, payload)

    /** Block until this instance completes (or the timeout expires). Returns the final snapshot, or `None` if the
      * instance was not found.
      *
      * @see
      *   [[WorkflowCapability.waitForCompletion]]
      */
    def waitForCompletion(timeout: FiniteDuration)(using cap: WorkflowCapability): Option[WorkflowSnapshot] =
      cap.waitForCompletion(id, timeout)

    /** Purge this instance's state from the state store. Returns `true` if purged.
      *
      * @see
      *   [[WorkflowCapability.purge]]
      */
    def purge()(using cap: WorkflowCapability): Boolean =
      cap.purge(id)
