//> using target.platform "jvm"
package dapr4s.derivation

import dapr4s.*
import java.time.Instant

/** JVM half of [[Forwarders]] — the runtime forwarders for the JVM-only [[dapr4s.JobsCapability]] (the Dapr JS SDK has
  * no jobs API; see `DaprCapabilityPlatform`). Inherited by `object Forwarders`, so code generated by the JVM-only
  * `Jobs.derive` macro calls plain `Forwarders.jobSchedule`/`jobScheduleOnce`/`jobGet`. The Scala.js twin of this trait
  * is empty.
  *
  * WHY @assumeSafe: same reason as on [[Forwarders]] itself — the forwarders call into `@assumeSafe` capability trait
  * methods on behalf of generated code.
  */
@scala.caps.assumeSafe
trait ForwardersPlatform:

  // ---- Jobs -----------------------------------------------------------------

  def jobSchedule[T](
      cap: JobsCapability,
      name: JobName,
      data: T,
      schedule: JobSchedule,
      dueTime: Option[Instant],
      repeats: Option[Int],
      ttl: Option[Instant],
      codec: JsonCodec[T],
  ): Unit =
    given JsonCodec[T] = codec
    cap.schedule[T](name, data, schedule, dueTime, repeats, ttl)

  def jobScheduleOnce[T](
      cap: JobsCapability,
      name: JobName,
      data: T,
      dueTime: Instant,
      ttl: Option[Instant],
      codec: JsonCodec[T],
  ): Unit =
    given JsonCodec[T] = codec
    cap.scheduleOnce[T](name, data, dueTime, ttl)

  def jobGet(cap: JobsCapability, name: JobName): Option[JobDetails] =
    cap.get(name)
