package dapr4s.internal

import dapr4s.*
import unsafeExceptions.canThrowAny

/** Internal bridge: wraps a [[Workflow]] instance for registration with the Dapr Java SDK.
  *
  * The SDK's instance-based `registerWorkflow(T)` overload uses the canonical class name of the registered object.
  * Since all bridges share the same class, we use the named overload `registerWorkflow(name, instance, ...)` with the
  * user workflow's simple class name as the name (e.g. `"OrderProcessingWorkflow"`, not
  * `"workflows.OrderProcessingWorkflow"`), so that `WorkflowCapability.start(WorkflowName("OrderProcessingWorkflow"))`
  * and the HTTP API URL match naturally.
  *
  * '''Invariant''': `w.run` must never be wrapped in a try/catch that intercepts
  * `io.dapr.durabletask.interruption.OrchestratorBlockedException` or
  * `io.dapr.durabletask.interruption.ContinueAsNewInterruption`. Both are control-flow signals thrown by the
  * durabletask runtime itself; swallowing either corrupts the orchestration state.
  */
@scala.caps.assumeSafe
private[dapr4s] final class WorkflowBridge(
    private val workflow: Workflow,
) extends io.dapr.workflows.Workflow:

  final override def create(): io.dapr.workflows.WorkflowStub | Null =
    val w = workflow
    new io.dapr.workflows.WorkflowStub:
      // OrchestratorBlockedException and ContinueAsNewInterruption must not be caught here.
      override def run(javaCtx: io.dapr.workflows.WorkflowContext | Null): Unit =
        if javaCtx != null then
          given WorkflowContext = new WorkflowContextImpl(javaCtx)
          w.run

/** Internal bridge: wraps a [[WorkflowActivity]] instance for registration with the Dapr Java SDK.
  *
  * Uses instance-based `registerActivity(name, instance)` so that the activity is registered under the user's canonical
  * class name, matching the name generated by [[WorkflowContextImpl.callActivity]].
  */
@scala.caps.assumeSafe
private[dapr4s] final class WorkflowActivityBridge[I, O](
    private val activity: WorkflowActivity[I, O],
) extends io.dapr.workflows.WorkflowActivity:

  final override def run(ctx: io.dapr.workflows.WorkflowActivityContext | Null): AnyRef | Null =
    if ctx == null then null
    else
      val rawInput = ctx.getInput(classOf[String]) match
        case null  => "null"
        case other => other
      val input = activity.inputCodec.decode(rawInput) match
        case Right(v)  => v
        case Left(err) => throw RuntimeException(s"Failed to decode activity input for '${activity.getClass.getSimpleName}'", err)
      val output = activity.execute(input)
      activity.outputCodec.encode(output)
