package dapr.safe.internal

import dapr.safe.*
import unsafeExceptions.canThrowAny

/** Internal bridge: wraps a [[Workflow]] instance for registration with the Dapr Java SDK.
  *
  * The SDK's instance-based `registerWorkflow(T)` overload uses the canonical class name of the registered object.
  * Since all bridges share the same class, we use the named overload `registerWorkflow(name, instance, ...)` with the
  * user workflow's canonical class name as the name, so that `WorkflowCapability.start(WorkflowName(...))` matches.
  */
@scala.caps.assumeSafe
private[safe] final class WorkflowBridge(
    private val workflow: Workflow,
) extends io.dapr.workflows.Workflow:

  final override def create(): io.dapr.workflows.WorkflowStub | Null =
    val w = workflow
    new io.dapr.workflows.WorkflowStub:
      override def run(javaCtx: io.dapr.workflows.WorkflowContext | Null): Unit =
        if javaCtx != null then
          given WorkflowContext = new WorkflowContextImpl(javaCtx)
          w.run()

/** Internal bridge: wraps a [[WorkflowActivity]] instance for registration with the Dapr Java SDK.
  *
  * Uses instance-based `registerActivity(name, instance)` so that the activity is registered under the user's canonical
  * class name, matching the name generated by [[WorkflowContextImpl.callActivity]].
  */
@scala.caps.assumeSafe
private[safe] final class WorkflowActivityBridge[I, O](
    private val activity: WorkflowActivity[I, O],
) extends io.dapr.workflows.WorkflowActivity:

  final override def run(ctx: io.dapr.workflows.WorkflowActivityContext | Null): AnyRef | Null =
    if ctx == null then null
    else
      val rawInput = ctx.getInput(classOf[String]) match
        case null  => "null"
        case other => other
      val input = activity.inputCodec
        .decode(rawInput)
        .getOrElse(
          throw RuntimeException(
            s"Failed to decode activity input for '${activity.getClass.getSimpleName}'",
          ),
        )
      val output = activity.execute(input)
      activity.outputCodec.encode(output)
