package dapr4s.internal

import dapr4s.*
import unsafeExceptions.canThrowAny

/** Internal bridge: wraps a [[Workflow]] instance for registration with the Dapr Java SDK.
  *
  * The SDK's instance-based `registerWorkflow(T)` overload uses the canonical class name of the registered object.
  * Since all bridges share the same class, we use the named overload `registerWorkflow(name, instance, ...)` with the
  * user workflow's simple class name as the name (e.g. `"OrderProcessingWorkflow"`, not
  * `"workflows.OrderProcessingWorkflow"`), so that `WorkflowCapability.start(WorkflowName("OrderProcessingWorkflow"))`
  * and the HTTP API URL match naturally.
  *
  * '''Invariant''': `w.run` must never be wrapped in a try/catch that intercepts
  * `io.dapr.durabletask.interruption.OrchestratorBlockedException` or
  * `io.dapr.durabletask.interruption.ContinueAsNewInterruption`. Both are control-flow signals thrown by the
  * durabletask runtime itself; swallowing either corrupts the orchestration state.
  */
@scala.caps.assumeSafe
private[internal] final class WorkflowBridge(
    private val workflow: Workflow,
) extends io.dapr.workflows.Workflow:

  final override def create(): io.dapr.workflows.WorkflowStub | Null =
    new io.dapr.workflows.WorkflowStub:
      // OrchestratorBlockedException and ContinueAsNewInterruption must not be caught here.
      override def run(javaCtx: io.dapr.workflows.WorkflowContext | Null): Unit =
        if javaCtx != null then
          given WorkflowContext = new WorkflowContextImpl(javaCtx)
          workflow.run

/** Internal bridge: wraps a [[WorkflowActivity]] instance for registration with the Dapr Java SDK.
  *
  * Uses instance-based `registerActivity(name, instance)` so that the activity is registered under its
  * [[dapr4s.WorkflowActivity.activityName]] (the simple class name by default), matching the name generated by
  * [[WorkflowContextImpl.callActivity]].
  */
@scala.caps.assumeSafe
private[internal] final class WorkflowActivityBridge[I, O](
    private val activity: WorkflowActivity[I, O],
    // WHY AnyRef: a DaprCapability carries a non-empty CC capture set, so storing it as a
    // typed field would force that capture into the bridge instance (and into the plain
    // collection that holds it). Storing it capture-erased — the same trick as
    // Subscription.rawHandler — keeps the bridge CC-opaque; we cast back at use under
    // @assumeSafe. The capability lives for the whole server lifetime (the enclosing
    // Dapr.serve scope), so reusing it for every activity invocation is sound.
    private val daprRef: AnyRef,
) extends io.dapr.workflows.WorkflowActivity:

  final override def run(ctx: io.dapr.workflows.WorkflowActivityContext | Null): AnyRef | Null =
    if ctx == null then null
    else
      val rawInput = ctx.getInput(classOf[String]) match
        case null  => "null"
        case other => other
      val input = activity.inputCodec.decode(rawInput) match
        case Right(v)  => v
        case Left(err) =>
          throw RuntimeException(s"Failed to decode activity input for '${activity.getClass.getSimpleName}'", err)
      val output = activity.execute(input)(using daprRef.asInstanceOf[DaprCapability])
      activity.outputCodec.encode(output)
