package dapr.safe

import language.experimental.safe

/** Unique identifier of a workflow instance.
  *
  * Auto-generated by [[WorkflowCapability.start]] when not specified, or supplied explicitly via
  * [[WorkflowCapability.startWithId]]. Used to target subsequent operations such as [[WorkflowCapability.getStatus]],
  * [[WorkflowCapability.suspend]], [[WorkflowCapability.resume]], [[WorkflowCapability.terminate]], and
  * [[WorkflowCapability.raiseEvent]]. May be empty when auto-generated (the sidecar assigns a UUID-based value).
  */
opaque type WorkflowInstanceId = String
object WorkflowInstanceId:
  def apply(s: String): WorkflowInstanceId = s
  extension (id: WorkflowInstanceId) def value: String = id
