apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    # See statestore.yaml for the ${DAPR4S_IT_REDIS_HOST} substitution.
    - name: redisHost
      value: ${DAPR4S_IT_REDIS_HOST}
    - name: redisPassword
      value: ""
